---
# Default ports
caddy_regular_http_port: 80
caddy_routed_http_port: 8080
caddy_regular_https_port: 443
caddy_routed_https_port: 8443

# Vhost discovery
caddy_discover_vhosts: true
caddy_tls: []
caddy_http: []

# CRS tuning
caddy_paranoia_level: 3
caddy_anomaly_threshold_inbound: 3
caddy_anomaly_threshold_outbound: 2
