[coroza_waf_apache_nginx]
# waf_apache_nginx_1 ansible_host=192.168.56.102 ansible_user=root ansible_ssh_pass=1234
waf_apache_nginx_2 ansible_host=192.168.56.101 ansible_user=root ansible_ssh_pass=1234