- name: Setup Caddy WAF
  hosts: coroza_waf_apache_nginx
  become: true
  roles:
    - role: caddy_waf_apache_nginx
  vars:
    caddy_regular_http_port: 80
    caddy_routed_http_port: 8080
    caddy_regular_https_port: 443
    caddy_routed_https_port: 8443
    caddy_log_output: /var/log/caddy/caddy.log # You can change this to a file path if you want to log to a file instead of stderr.
    caddy_paranoia_level: 4 # CRS paranoia level (1-4, higher is stricter)
    caddy_anomaly_threshold_inbound: 3 # Inbound anomaly score threshold (lower is stricter)
    caddy_anomaly_threshold_outbound: 2 # Outbound anomaly score threshold (lower is stricter)
    caddy_discover_vhosts: true
    caddy_tls: []
