---
- name: Coppy Caddy static binary to host
  ansible.builtin.copy:
    src: caddy_coraza
    dest: /bin/caddy
    mode: "0755"
    owner: root
    group: root

- name: Create systemd service for Caddy
  ansible.builtin.copy:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service
    mode: "0644"
  notify:
    - Reload systemd daemon
    - Restart Caddy

- name: Ensure Caddy dir
  ansible.builtin.file:
    path: "/etc/caddy/"
    state: directory
    mode: "0644"
    owner: root
    group: root

- name: Ensure Caddy log directory exists
  ansible.builtin.file:
    path: /var/log/caddy
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure Caddy storage directory exists
  ansible.builtin.file:
    path: /var/lib/caddy
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy vhost discovery script
  ansible.builtin.copy:
    src: discover_vhosts.sh
    dest: /usr/local/bin/discover_vhosts.sh
    mode: "0755"
    owner: root
    group: root

- name: Run vhost discovery subtask
  ansible.builtin.include_tasks:
    file: discover_vhosts.yml

- name: Copy base caddyfile with http(s) configuration
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: '0644'
    owner: root
  notify:
    - Restart Caddy
    - Reload config

- name: Redirect incoming HTTP traffic to Caddy
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: "{{ caddy_regular_http_port }}"
    jump: REDIRECT
    to_ports: "{{ caddy_routed_http_port }}"
    state: present

- name: Redirect incoming HTTPS traffic to Caddy
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: "{{ caddy_regular_https_port }}"
    jump: REDIRECT
    to_ports: "{{ caddy_routed_https_port }}"
    state: present

- name: Allow inbound traffic on port caddy_routed_http_port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ caddy_routed_http_port }}"
    jump: ACCEPT
    state: present

- name: Allow inbound traffic on port caddy_routed_https_port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ caddy_routed_https_port }}"
    jump: ACCEPT
    state: present

- name: Enable and start Caddy service
  ansible.builtin.systemd:
    name: caddy
    enabled: true
  notify:
    - Restart Caddy
    - Reload config
